### ISSUE TITLE
Support wait for completion for CloudEnvironment

### ISSUE THREAD

**Issue by maxsxu** [streamnative/terraform-provider-streamnative#37]
### Description
Add `wait_for_completion` argument. 
If true will block until the status of CloudEnvironment has a Ready condition. Default to true.

We should support:
- Block until creation and update complete
- Block until deletion complete, this is required when cleaning up CloudConnection and CloudEnvironment in one destroy

Implementation refer: https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/job.html#wait_for_completion

**Comment by mitch-hamm** [comment]
Inital PR https://github.com/streamnative/terraform-provider-streamnative/pull/41

**Comment by mitch-hamm** [comment]
@maxsxu Did we want a similar mechanism in place for CloudConnection as well?
