### ISSUE TITLE
[feat]: support provider auth with string parameters

### ISSUE THREAD

**Issue by ericsyh** [streamnative/terraform-provider-streamnative#45]
### Background

For now, the sn terraform provider only supports `key_file_path` as the provider auth, but for some secture scenarios using the file path means users need to store the file in some places and may have leak risks. So, ideally should support the provider auth with string parametres and support the env parameters to pass.

### Solution 

We can support sn provider auth with `client_id` and `client_secret`. 

Usage with provider parameters

```
provider "streamnative" {
    client_id = "5HITm7RKuV8JlwzAk83lkm4M"
    client_secret = "JJusCALj8xxxxxxxxdAxxxxxxxrEZdC7LyF1AYv5co"
} 
```
Usage with env parameters
```
% export STREAMNATIVE_CLIENT_ID="5HITm7RKuV8JlwzAk83lkm4M"
% export STREAMNATIVE_CLIENT_SECRET="JJusCALj8xxxxxxxxdAxxxxxxxrEZdC7LyF1AYv5co"
terraform plan
```

**Comment by saurabh31090** [comment]
Hi @ericsyh  Even after removing the key_file_path from both the provider block and the variable file, when I execute the terraform plan command, it continues to prompt for the key_file_path. Subsequently, when I provide the name of a dummy file, an error occurs indicating that the file's code is incorrect.
<img width="563" alt="SN1" src="https://github.com/streamnative/terraform-provider-streamnative/assets/40741661/14176e00-bda9-4107-91cc-3e82e4334fe3">

Provider block 
terraform {
  required_providers {
    streamnative = {
      source = "streamnative/streamnative"
      version = "0.2.0"
    }

  }
}

provider "streamnative" {
        client_id = "var.STREAMNATIVE_CLIENT_ID"
        client_secret = "var.STREAMNATIVE_CLIENT_SECRET"
        client_email = "var.STREAMNATIVE_CLIENT_EMAIL"
}

**Comment by ericsyh** [comment]
> Even after removing the key_file_path from both the provider block and the variable file, when I execute the terraform plan command, it continues to prompt for the key_file_path. Subsequently, when I provide the name of a dummy file, an error occurs indicating that the file's code is incorrect.

@saurabh31090 this is a feature plan to implement but not yet supported.

**Comment by urfreespace** [comment]
already supported with this PR: https://github.com/streamnative/terraform-provider-streamnative/pull/47 @ericsyh PTAL
